#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "~/.Xmodmap"

##################################################################
# Applications you want to run with fluxbox.                     #
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.#
##################################################################
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
xcompmgr & 
fbsetbg -f .fluxbox/backgrounds/dotfileswall.jpg & # Sets a background using fbsetbg
tint2 & # Starts the tint2 taskbar
conky & # Starts conky
redshift & # Starts redshift
wicd-gtk &
dropboxd &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/nate/.fluxbox/log"
